# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
sudo: required

env:
  global:
    - CRATE_NAME=rad

matrix:
  include:
    - os: linux
      rust: nightly

before_install:
  - set -e
  - rustup self update

script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  - export RUSTDOCFLAGS="-Cpanic=abort"
  - cargo install grcov
  - cargo build --verbose --workspace 
  - cargo test --verbose --workspace 
  - |
    grcov ./target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing -o ./target/debug/coverage;
    bash <(curl -s https://codecov.io/bash) -f ./target/debug/coverage;

branches:
  only:
    - master

notifications:
  email:
    - malyshev13091995@gmail.com
