# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
sudo: required

env:
  global:
    - CRATE_NAME=rad

matrix:
  include:
    - os: linux
      rust: stable

before_install:
  - set -e
  - rustup self update

install:
  - cargo install cargo-tarpaulin

script:
  - cargo build --verbose --workspace 
  - cargo test --verbose --workspace 

after_success: |
    cargo tarpaulin --out Xml;
    bash <(curl -s https://codecov.io/bash);

branches:
  only:
    - master

notifications:
  email:
    - malyshev13091995@gmail.com
